name: resqlink
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  path: ^1.8.0
  provider: ^6.1.5
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  sqflite: ^2.3.0
  geolocator: ^14.0.1
  flutter_local_notifications: ^19.2.1
  firebase_core: ^3.14.0
  firebase_database: ^11.3.7 # For Firebase authentication
  cloud_firestore: ^5.6.9 # For Firebase Firestore (if needed)
  firebase_auth: ^5.6.0
  wifi_iot: ^0.3.19
  nearby_connections: ^4.3.0
  permission_handler: ^11.3.1
  connectivity_plus: ^5.0.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  audioplayers: ^5.2.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/1.png
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf
