name: resqlink
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  english_words: ^4.0.0
  path: ^1.8.0
  provider: ^6.1.5
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  sqflite: ^2.3.0
  geolocator: ^14.0.1
  flutter_local_notifications: ^19.2.1
  firebase_core: ^3.14.0
  firebase_database: ^11.3.7 # For Firebase authentication
  cloud_firestore: ^5.6.9 # For Firebase Firestore (if needed)
  firebase_auth: ^5.6.0
  wifi_direct_plugin: ^0.0.4
  permission_handler: ^12.0.1
  connectivity_plus: ^6.1.4
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  audioplayers: ^5.2.1
  auto_size_text: ^3.0.0
  battery_plus: ^6.2.2
  cupertino_icons: ^1.0.6
  vibration: ^3.1.3
  device_info_plus: ^11.5.0
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  flutter_map_tile_caching: ^10.1.1
  path_provider: ^2.1.5
  http: ^1.5.0
  wifi_scan: ^0.4.1+2
  wifi_iot: ^0.3.19+2
  web_socket_channel: ^3.0.3
  network_info_plus: ^6.1.4
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  multicast_dns: ^0.3.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/1.png
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rajdhani-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rajdhani-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rajdhani-Bold.ttf
          weight: 700

    # Body text font - Highly readable
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

    # Monospace font for technical data
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
