// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
    appId: '1:1056797390668:web:your_web_app_id_here',
    messagingSenderId: '1056797390668',
    projectId: 'resqlink-2e060',
    authDomain: 'resqlink-2e060.firebaseapp.com',
    storageBucket: 'resqlink-2e060.appspot.com',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
    appId: '1:1056797390668:android:74c09cc7186b11c0aa81e9',
    messagingSenderId: '1056797390668',
    projectId: 'resqlink-2e060',
    authDomain: 'resqlink-2e060.firebaseapp.com',
    storageBucket: 'resqlink-2e060.appspot.com',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:1056797390668:ios:your_ios_app_id_here',
    messagingSenderId: '1056797390668',
    projectId: 'resqlink-2e060',
    authDomain: 'resqlink-2e060.firebaseapp.com',
    storageBucket: 'resqlink-2e060.appspot.com',
    iosBundleId: 'com.example.resqlink',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:1056797390668:ios:your_ios_app_id_here',
    messagingSenderId: '1056797390668',
    projectId: 'resqlink-2e060',
    authDomain: 'resqlink-2e060.firebaseapp.com',
    storageBucket: 'resqlink-2e060.appspot.com',
    iosBundleId: 'com.example.resqlink',
  );
}
